---
site_name: PyFortinet
site_description: Python library for Fortinet API handling
site_author: Viktor Kertesz
site_url: https://pyfortinet.github.io/

repo_name: viktorkertesz/pyfortinet
repo_url: https://github.com/viktorkertesz/pyfortinet

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select

extra_css:
  - extra.css

nav:
  - PyFortinet: index.md
  - User Guide:
      - Quick Start Guide: user_guide/quickstart.md
      - Installation: user_guide/installation.md
      - Basic Usage: user_guide/basic_usage.md
  - Developer Guide:
      - Lab setup: developer_guide/lab_setup.md
      - FMG API guide: developer_guide/fmg_api_objects.md
  - Code Reference: reference/

plugins:
- search
- gen-files:
    scripts:
      - docs/gen_ref_pages.py
- mkdocstrings:
    handlers:
      python:
        paths: [ pyfortinet ]
        options:
          show_signature_annotations: true
          signature_crossrefs: true
          # add __init__ args to class and ignore __init__ summary text
          merge_init_into_class: true
          docstring_options:
            ignore_init_summary: true
- section-index
- literate-nav

watch:
    - pyfortinet

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
