---
site_name: PyFortinet
site_description: Python library for Fortinet API handling
site_author: Viktor Kertesz
site_url: https://pyfortinet.github.io/

repo_name: viktorkertesz/pyfortinet
repo_url: https://github.com/viktorkertesz/pyfortinet

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select

extra_css:
  - extra.css
  - code_select.css

nav:
  - PyFortinet: index.md
  - User Guide:
      - Quick Start Guide: user_guide/quickstart.md
      - Installation: user_guide/installation.md
      - Basic Usage: user_guide/basic_usage.md
  - Developer Guide:
      - General guide: developer_guide/index.md
      - Lab setup: developer_guide/lab_setup.md
      - FMG API guide: developer_guide/fmg_api_objects.md
      - Testing: developer_guide/testing.md
  - Code Reference: reference/

plugins:
- search
- autorefs
- gen-files:
    scripts:
      - docs/gen_ref_pages.py
- mkdocstrings:
    handlers:
      python:
        paths: [ pyfortinet ]
        options:
          line_length: 120
          separate_signature: true
          show_signature_annotations: true
          signature_crossrefs: true
          # add __init__ args to class and ignore __init__ summary text
          merge_init_into_class: true
          docstring_options:
            ignore_init_summary: true
          members: true
          show_labels: true
          group_by_category: true
          parameter_headings: false
          filters:
            - "!^_"  # exclude private members
            - "^__init__$"
            - "^_url$"
            - "^_fmg$"
#         still INSIDER features
#          summary: true
#          extensions:
#            - griffe_pydantic:
#                schema: true

- section-index
- literate-nav

watch:
    - pyfortinet

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
