name: Publish to PyPi
on:
  workflow_dispatch:

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      # retrieve your distributions here
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Install flit and build project
        run: |
          pip install flit
          flit build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
